coverage:
  status:
    project: off
    patch:
      default:
        threshold: 1%

ignore:
  - "**/*.pb.go"
  - "**/*.gw.go"
  - "**/*_test.go"
  - "**/testexchange/**"

fixes:
  - "/enigma-core::"

comment:
  layout: "diff"